# Generated by Django 4.2.6 on 2023-11-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=25)),
                ('fecha_publicacion', models.PositiveIntegerField()),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('autores', models.ManyToManyField(to='libreria.autor')),
            ],
        ),
    ]
