# Generated by Django 4.2.6 on 2023-11-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.autor'),
        ),
    ]
