# Generated by Django 4.2.6 on 2023-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_libro_autores_alter_libro_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autores',
            new_name='autor',
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='../portadas/'),
        ),
    ]
